config/routes.rb
Rails.application.routes.draw do
  resources :weathers

  root 'diaries#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => "sessions#new"

  resources :diaries do
    collection do
      get 'admin_index'
      post 'upload'
    end
  end

  resources :categories

  get 'monthly/:year/:month' => 'monthly#index', :as => "monthly" , :constraints => {:year=>/\d{4}/, :month=>/\d{1,2}/}

  get 'category/:id' => 'category#index', :as =>"diary_category"

  get 'rss' => 'rss#index'

  get 'log' => "log#production"
  get 'log/production' => "log#production"
  get 'log/access' => "log#access"
  get 'log/error' => "log#error"

end

app/controllers/log_controller.rb
class LogController < ApplicationController
  before_action :set_log

  def production
    common_render
  end

  def access
    common_render
  end

  def error
    common_render
  end


  private
  def set_log
    path = Settings.log_path[action_name]

    if path.nil? then return end

    @log = []
    File.open(path) {|file|
      while row = file.gets
        @log << row
      end
    }

    @log_txt = File.open(path).read
  end

  def common_render
    respond_to do |format|
      format.html {render :index}
      format.txt  {render :text => @log_txt}
    end
  end

end

app/helpers/log_helper.rb
module LogHelper

 def active?(name)
   return "active" if name == action_name
 end

end

app/views/log/index.html.erb
<% provide :title, controller_name + " [#{action_name}]" %>


<div id="log-content" class="panel panel-default">

  <ul class="nav nav-tabs nav-justified">
    <li class="<%= active?("production") %>"><%= link_to "tmp/production.log", log_production_path %></li>
    <li class="<%= active?("access") %>"><%= link_to "httpd/access.log", log_access_path %></li>
    <li class="<%= active?("error") %>"><%= link_to "httpd/error.log", log_error_path %></li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
        text <span class="caret"></span>
      </a>

      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "production.txt", log_production_path(:format => :txt) %></li>
        <li><%= link_to "access.txt", log_access_path(:format => :txt) %></li>
        <li><%= link_to "error.txt", log_error_path(:format => :txt) %></li>
      </ul>

    </li>


  </ul>


  <% if @log %>
  <table class="table content">
    <% i = 1 %>
    <% @log.last(50).each do |row|  %>
    <tr>
      <td><%= i %></td>
      <td><%= row %></td>
    </tr>

    <% i = i + 1 %>

    <% end %>
  </table>
  <% end %>

</div>