config/routes.rb
Rails.application.routes.draw do
  resources :weathers

  root 'diaries#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => "sessions#new"

  resources :diaries do
    collection do
      get 'admin_index'
      post 'upload'
    end
  end

  resources :categories

  get 'monthly/:year/:month' => 'monthly#index', :as => "monthly" , :constraints => {:year=>/\d{4}/, :month=>/\d{1,2}/}

  get 'category/:id' => 'category#index', :as =>"diary_category"

  get 'rss' => 'rss#index'

  get 'log' => "log#production"
  get 'log/production' => "log#production"
  get 'log/access' => "log#access"
  get 'log/error' => "log#error"

end

app/models/diary.rb
class Diary < ActiveRecord::Base
  belongs_to :category
  belongs_to :weather

  validates :authored_on, :title, :body, :category_id, presence: true


  #年月検索
  def self.year_month(year,month)
    self.where(["year(authored_on) = ? and month(authored_on) = ?", year, month])
  end

  #年別の集計SQL
  def self.year_list
    self.select("year(authored_on) as year")
    .group("year(authored_on)")
    .order("authored_on desc")
  end

  #月別の集計SQL
  def self.monthly_list
    self.select("year(authored_on) as year","month(authored_on) as month")
    .group("year(authored_on)","month(authored_on)")
    .order("authored_on desc")
  end

  #通常検索
  def self.default(page)
    self.includes(:category,:weather)
    .order(authored_on: :desc)
    .page(page)
    .per(5)
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]
  before_action :login_check, except: [:index, :show]


  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.default(params[:page])
  end

  def admin_index
    @diaries = Diary.page(params[:page]).per(30).order("authored_on desc")
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
    @prev = Diary.where("authored_on < ?", @diary.authored_on).order("authored_on desc").limit(1).first
    @next = Diary.where("? < authored_on", @diary.authored_on).order("authored_on desc").limit(1).first
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to admin_index_diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # Post /diaries/upload
  def upload
    file = params[:image][:file]
    name = file.original_filename
    path = "public/img"

    FileUtils.mkdir(path) unless File.exists?(path)
    File.open(path + "/" + name , 'wb') { |f|
      f.write(file.read)
    }

    render json: {:file_name => name}, :status => :ok
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_diary
    @diary = Diary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def diary_params
    params.require(:diary).permit(:authored_on, :category_id, :title, :body, :weather_id, :mt_id)
  end

end

app/helpers/diaries_helper.rb
module DiariesHelper

  def convert_content(str)
    str = pre_escape(str)
    str = br(str)
    str = responsive_embed(str)
    str = Sanitize.clean(str, Sanitize::Config::RELAXED_CUSTOM)
    str.html_safe
  end

  #本文から概要の生成
  #最大124文字
  def get_description(str)
    doc = Nokogiri::HTML(str)
    doc.inner_text.gsub(/\r\n?/, " ").slice(0,64)
  end

  def weather_icon(file_name)
    image_tag("weathers/" + file_name, :size => "22x22", :class => "weather")
  end

  def br(str)
    if str then (str).gsub(/(\r\n?)|(\n)/, "<br />") end
  end

  #last.fmからデータ取得
  def get_recent_track

    # if Rails.env == "development"
    #   return LastFm.new()
    # end

    cache_expire = Settings.last_fm[:expire_hour].to_i.hour

    begin
      info = Rails.cache.fetch("last_fm_recent_track", expires_in: cache_expire) do
        LastFm.new()
      end
    rescue => e
      return nil
    end
  end

  #[Caching with Rails: An overview — Ruby on Rails Guides] http://guides.rubyonrails.org/caching_with_rails.html
  def cache_key_for_lastfm(last_fm)
    last_fm.created_at.to_number
  end


  private
  def responsive_embed(str)
    #<div class="embed-responsive embed-responsive-16by9">
    doc = Nokogiri::HTML(str)
    doc.css("iframe").wrap('<div class="embed-responsive embed-responsive-16by9">')
    doc.css("body").inner_html
  end

  #preタグ内のみエスケープする
  def pre_escape(str)
    if str.nil? then return end

    tags = str.scan(/<pre>[\s|\S]*?<\/pre>/)
    tags.each do |item|
      item.gsub!(/(<pre>|<\/pre>)/,"")
      escape_item = ERB::Util.html_escape(item)
      escape_item.gsub!(/(^\r\n|\r\n$)/,"")
      str.gsub!(item,escape_item)
    end

    str
  end

end

app/views/diaries/_content.erb
<div class="diary-content panel panel-default">
	<div class="panel-body">
		<div>
			<h1 class="diary-title page-header">
				<%= link_to diary.title, diary %>
			</h1>
			<div class="diary-body"><%= convert_content(diary.body) %></div>
			<div class="diary-footer">
				<div class="col-md-6">
					<a href="<%= unless diary then diary_category_path(diary.category_id) end %>">
						<span class="glyphicon glyphicon-tag"></span>
						<span class="diary-category"><%= if diary.category_id then diary.category.name end %></span>
					</a>
				</div>
				<div class="text-right col-md-6">
					<span class="diary-authored"><%= to_strf(diary.authored_on) %></span>
					<span class="diary-weather"><%= if diary.weather_id then weather_icon(diary.weather.file_name) end %><span>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/diaries/_form.html.erb
<%= form_for(@diary, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
<% if @diary.errors.any? %>
<div class="alert alert-danger alert-dismissable" role="alert">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<h4><%= pluralize(@diary.errors.count, "error") %> prohibited this diary from being saved:</h4>

	<ul>
		<% @diary.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group">
	<%= f.label :authored_on, :class => "col-sm-2 control-label" %>
	<div class="col-sm-2">
		<%= f.text_field :authored_on, :value => @diary.authored_on.nil? ? Time.now.strftime("%Y-%m-%d %H:%M") : @diary.authored_on.strftime("%Y-%m-%d %H:%M") , :class => "form-control" %>
	</div>
	<div class="col-sm-2 category">
		<%= f.select :category_id, Category.order(:no).map{|t| [t.name, t.id]}, {} , {:class => "show-tick"} %>
	</div>
	<div class="col-sm-6 weather">
		<%= f.select :weather_id, Weather.all.map{|t| [t.name, t.id]}, {} , {:class => "show-tick"} %>
		<div class="btn-group" role="group">
			<% Weather.all.each do |t| %>
			<button type="button" class="btn btn-default"><%= weather_icon(t.file_name) %></button>
			<% end %>
		</div>

	</div>
</div>
<div class="form-group">
	<%= f.label :title, :class => "col-sm-2 control-label" %>
	<div class="col-sm-10">
		<%= f.text_field :title, :class => "form-control" %>
	</div>
</div>
<div class="form-group">
	<%= f.label :body, :class => "col-sm-2 control-label" %>
	<div class="col-sm-10">
		<%= f.text_area :body, :size => "30x10", :class => "form-control" %>
	</div>
</div>


<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<%= f.submit :class => "btn btn-primary" %>
	</div>

	<div class="image-upload col-sm-7 input-group">
		<input id="dummy_file" type="text" class="form-control" placeholder="select image">
		<span class="input-group-btn">
			<button id="remove" class="btn btn-default" type="button" style="display:none">
				<span class="glyphicon glyphicon-trash"></span>
				Remove
			</button>

			<button id="upload" class="btn btn-default" type="button" style="display:none">
				<span class="glyphicon glyphicon-open"></span>
				Upload
			</button>

			<button id="browse" class="btn btn-primary" type="button">
				<span class="glyphicon glyphicon-folder-open"></span>
				Browse...
			</button>
		</span>
	</div>
</div>


<div class="diary col-sm-offset-2">
	<div class="well well-sm text-center">preview</div>
	<%= render "content", :diary => @diary %>
</div>


<% end %>


<%= form_tag({action: "upload"}, remote: true, authenticity_token: true,  id: "image-upload-form") do %>
<%= file_field :image, :file, :class=>"hide" %>
<% end %>

app/views/diaries/admin_index.html.erb
<% content_for :title do params[:action] end %>

<div class="page-header">

	<%= link_to new_diary_path, :class => 'btn btn-default' do %>
	<span class="glyphicon glyphicon-list-alt"></span>
	New
	<% end %>


	<%= link_to diaries_path, :class => 'btn btn-default' do %>
	<span class="glyphicon glyphicon-list-alt"></span>
	Top
	<% end %>
	<h1>Admin Index</h1>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>id</th>
				<th>title</th>
				<th>authored_on</th>
				<th>created_at</th>
				<th>updated_at</th>
			</tr>
		</thead>

		<tbody>
			<% @diaries.each do |diary| %>
			<tr>
				<td><%= diary.id %></td>
				<td><%= diary.title %></td>
				<td><%= to_strf(diary.authored_on) %></td>
				<td><%= to_strf(diary.created_at) %></td>
				<td><%= to_strf(diary.updated_at) %></td>
				<td> <%= link_to 'Show', diary %></td>
				<td> <%= link_to 'Edit', edit_diary_path(diary) %></td>
				<td> <%= link_to 'Destroy', diary, data: { confirm: 'Are you sure?' },:method => :delete %></td>

			</tr>

			<% end %>
		</tbody>
	</table>
</div>

<div id="diary-paginate">
	<%=paginate @diaries, :theme=>'bootstrap3' %>
</div>

app/views/diaries/edit.html.erb
<% content_for :title do params[:action] end %>

<div class="diary-form">

	<div class="page-header">
		<a href="<%= diary_path(@diary) %>" class="btn btn-default" data-method="delete" rel="nofollow" data-confirm="Are you sure?">
			<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> del
		</a>
		<a href="<%= admin_index_diaries_path %>" class="btn btn-default"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> list</a>
		<a href="<%= diary_path(@diary) %>" class="btn btn-primary"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> show</a>
		<h1>Editing diary</h1>
	</div>

	<%= render 'form' %>

</div>

app/views/diaries/index.html.erb
<%

if request.parameters[:controller] == "monthly" then
	content_for :title do
		params[:year] + "/" + params[:month]
	end

	content_for :keywords do
		params[:year] + "/" + params[:month]
	end

	content_for :description do
		params[:year] + "年" + params[:month] + "月の日記一覧であるぞ"
	end

elsif request.parameters[:controller] == "category" then
	category = Category.find(params[:id])

	content_for :title do
		category.name
	end

	content_for :keywords do
		category.name
	end

	content_for :description do
		"カテゴリ：" + category.name + "の日記一覧であるぞ"
	end
end

%>

<div class="diary col-md-9 col-md-offset-1">
	<% @diaries.each do |item| %>
	<%= render 'diaries/content', diary: item %>
	<% end %>


	<div id="diary-paginate">
		<%=paginate @diaries, :theme=>'bootstrap3' %>
	</div>
</div>

<div id="sidebar" class="col-md-2">
	<%= render :partial => 'shared/sidebar' %>
</div>

app/views/diaries/new.html.erb
<% content_for :title do params[:action] end %>

<div class="diary-form">

	<div class="page-header">
		<%= link_to diaries_path, :class => 'btn btn-default' do %>
		<span class="glyphicon glyphicon-list-alt"></span>
		Back
		<% end %>
		<h1>New diary</h1>
	</div>

	<%= render 'form' %>

</div>

app/views/diaries/show.html.erb
<% content_for :title do @diary.title.html_safe end %>
<% content_for :keywords do @diary.category.name end %>
<% content_for :description do get_description(@diary.body) end %>

<% unless current_user.nil? %>
<div class="page-header">
  <a href="<%= admin_index_diaries_path %>" class="btn btn-default"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> list</a>
  <a href="<%= edit_diary_path(@diary) %>" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> edit</a>
  <h1>Show diary</h1>
</div>
<% end %>

<div class="diary col-md-9 col-md-offset-1">
  <%= render 'diaries/content', diary: @diary %>


  <ul class="nav nav-pills nav-justified">
    <li class="<%= if @next.nil? then "disabled" end %>">
      <%= link_to @next do %>
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> new
      <% end %>
    </li>

    <li>
      <%= link_to root_path do %>
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span> home
      <% end %>
    </li>

    <li class="<%= if @prev.nil? then "disabled" end %>">
      <%= link_to @prev do %>
      old <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
      <% end %>
    </li>

  </ul>

</div>


<div id="sidebar" class="col-md-2">
  <%= render :partial => 'shared/sidebar' %>
</div>