config/routes.rb
Rails.application.routes.draw do
  resources :weathers

  root 'diaries#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => "sessions#new"

  resources :diaries do
    collection do
      get 'admin_index'
      post 'upload'
    end
  end

  resources :categories

  get 'monthly/:year/:month' => 'monthly#index', :as => "monthly" , :constraints => {:year=>/\d{4}/, :month=>/\d{1,2}/}

  get 'category/:id' => 'category#index', :as =>"diary_category"

  get 'rss' => 'rss#index'

  get 'log' => "log#production"
  get 'log/production' => "log#production"
  get 'log/access' => "log#access"
  get 'log/error' => "log#error"

end

app/views/shared/_sidebar.html.erb
<div id="links">
	<ul>
		<li><a href="https://twitter.com/sheet00"><%= image_tag("icons/twitter.png", :size =>"25x25") %></a></li>
		<li><a href="https://soundcloud.com/sheet"><%= image_tag("icons/soundcloud.png", :size =>"25x25") %></a></li>
		<li><a href="https://www.flickr.com/photos/sheet00/"><%= image_tag("icons/flickr.png", :size =>"25x25") %></a></li>
		<li><a href="https://github.com/sheet00/"><%= image_tag("icons/github.png", :size =>"25x25") %></a></li>
	</ul>
</div>


<% track = get_recent_track %>
<% if controller_name == "diaries" and action_name == "index" and track %>
	<% cache track.created_at.strftime("%Y%m%d_%H%M%S") do %>
	<div id="last-fm">
		<h3 class="title">Last.fm</h3>
		<div><%= track.name %></div>
		<div>by:<%= track.artist %></div>
		<div>from:<%= track.album %></div>
		<% if track.image.presence %>
		<div class="image"><a href="<%= track.url %>" class="thumbnail"><%= image_tag track.image %></a></div>
		<% end %>
	</div>
	<% end %>
<% end %>



<div id="category-list">
	<h3 class="title">categories</h3>
	<ul class="nav nav-pills nav-stacked">
		<% Category.order(:no).each do |item| %>
		<li class="<%=if params[:controller] == "category" and params[:id] == item.id.to_s then "active" else nil end %>">
			<%= link_to item.name, diary_category_path(item.id) %>
		</li>
		<% end %>
	</ul>
</div>


<% unless controller_name == "diaries" and action_name == "show" %>
<div id="monthly-list">
	<h3 class="title">archives</h3>
	<ul class="year-list">
		<% monthly_list = Diary.monthly_list %>
		<% Diary.year_list.each do |row| %>
		<li>
			<a href="#" class="year"><%= row.year %></a>

			<ul class="month nav nav-pills nav-stacked" style="<%= if params[:year] == row.year.to_s then "display:block" else "display:none" end %>">
				<% monthly = monthly_list.select{|item| item.year == row.year} %>
				<% monthly.each do |item| %>
				<li class="<%=if params[:year] == item.year.to_s and params[:month] == item.month.to_s then "active" else nil end %>">
					<%= link_to Date.new(item.year,item.month,1).strftime("%B %Y"), monthly_path(item.year,item.month) %>
				</li>
				<% end %>
			</ul>
		</li>
		<% end %>

		<li>
			<a href="<%= url_for :controller => 'rss', :action => 'index', :format => 'xml' %>">
				<%= image_tag("icons/feed-icon.png", :size =>"14x14") %>
				<span id="rss">rss</span>
			</a>
		</li>
	</ul>
</div>
<% end %>


<% unless current_user.nil? %>
<div id="admin-menu">
	<h3 class="title">admin-menu</h3>
	<ul class="nav nav-pills nav-stacked">
		<li><a href="<%= new_diary_path %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>new diary</a></li>
		<li><a href="<%= admin_index_diaries_path %>"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>list</a></li>
		<li><a href="<%= categories_path %>"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span>category</a></li>
		<li><a href="<%= login_path %>"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>login</a></li>
		<li><a href="<%= weathers_path %>"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span>weather</a></li>
		<li><a href="<%= log_path %>"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>log</a></li>
	</ul>
</div>
<% end %>